# Generated by Django 3.1.2 on 2021-01-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210103_2347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='account',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='company_user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='removed',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='account',
            name='user_profile',
            field=models.IntegerField(default=0),
        ),
    ]
