# Generated by Django 3.1.2 on 2021-01-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210104_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='consult',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='create',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
