# Generated by Django 3.1.2 on 2021-01-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210104_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='block_number',
            field=models.IntegerField(default=0),
        ),
    ]
