# Generated by Django 3.1.2 on 2021-01-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_function_block_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='block_position',
            field=models.IntegerField(default=0),
        ),
    ]
