# Generated by Django 3.1.2 on 2021-01-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_function_block_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='has_child',
            field=models.BooleanField(default=0),
        ),
    ]
