# Generated by Django 3.1.2 on 2021-01-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20210113_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
