# Generated by Django 3.1.2 on 2021-01-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210113_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='departament_id',
            field=models.IntegerField(default=0),
        ),
    ]
