# Generated by Django 3.1.2 on 2021-01-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_departament_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField()),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('adress_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IVARegime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='contacts',
            name='IVA_regime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='NIF',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contacts',
            name='discount_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='general_discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='main_address',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='payment_method_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='pp_discount',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='surcharge',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='tariff_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='vacation_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='vacation_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='company_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
