# Generated by Django 3.1.2 on 2021-01-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20210118_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpirationAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='address_2',
            new_name='observations',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='removed',
            new_name='blocked',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='rep_id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='contacts',
            name='IRPF_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='billing_address',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='canon',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='credit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='credit_alert',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='email_bill',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='expiration_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='extra_warranty',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='franchise_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='generate_expiration',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='no_mailing',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='reseller',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='web_password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
