# Generated by Django 3.1.2 on 2021-01-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20210118_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='ADN_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='brands',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contacts',
            name='closing1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contacts',
            name='closing2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contacts',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contacts',
            name='intrested',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contacts',
            name='last_bill_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='last_note_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='last_visit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='manager_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='not_interested',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='observation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contacts',
            name='old_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='opening1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contacts',
            name='opening2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contacts',
            name='supliers',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contacts',
            name='tracking',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='visits',
            field=models.IntegerField(null=True),
        ),
    ]
