# Generated by Django 3.1.2 on 2021-01-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20210119_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='intrested',
            new_name='interested',
        ),
    ]
