# Generated by Django 3.1.2 on 2021-01-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20210119_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='user_type',
            new_name='contact_type',
        ),
    ]
