# Generated by Django 3.1.2 on 2021-01-19 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20210119_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='supliers',
            new_name='suppliers',
        ),
    ]
