# Generated by Django 3.1.2 on 2021-01-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='web_register',
            field=models.BooleanField(null=True),
        ),
    ]
