# Generated by Django 3.1.2 on 2021-01-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='is_franchise',
            field=models.BooleanField(null=True),
        ),
    ]
