# Generated by Django 3.1.2 on 2021-01-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_contacts_is_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='expirationalert',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ivaregime',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clienttype',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='interestcategory',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
    ]
