# Generated by Django 3.1.2 on 2021-01-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20210120_1718'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpirationAlert',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='credit_alert',
            field=models.BooleanField(null=True),
        ),
    ]
