# Generated by Django 3.1.2 on 2021-01-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_auto_20210120_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='IVA_type',
            field=models.IntegerField(null=True),
        ),
    ]
