# Generated by Django 3.1.2 on 2021-01-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_contacts_iva_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='adress_type',
            new_name='address_type',
        ),
    ]
