# Generated by Django 3.1.2 on 2021-01-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20210121_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='discount_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='expiration_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='general_discount',
            field=models.IntegerField(default=0),
        ),
    ]
