# Generated by Django 3.1.3 on 2021-01-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_auto_20210121_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='vacation_end',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='vacation_start',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
