# Generated by Django 3.1.2 on 2021-01-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='note',
            name='icon',
        ),
    ]
