# Generated by Django 3.1.2 on 2021-01-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_auto_20210126_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.IntegerField(default=0),
        ),
    ]
