# Generated by Django 3.1.2 on 2021-01-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_auto_20210126_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='portal_key',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
