# Generated by Django 3.1.2 on 2021-01-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_auto_20210128_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_check', models.BooleanField()),
                ('user_check', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hour', models.IntegerField()),
                ('contact_id', models.IntegerField()),
                ('concerted_visit', models.BooleanField()),
                ('commercial_request', models.BooleanField()),
                ('visit_ended', models.BooleanField()),
                ('observations', models.CharField(max_length=500)),
                ('internal_observations', models.CharField(max_length=500)),
                ('offert', models.CharField(max_length=500)),
                ('public_sale', models.BooleanField()),
                ('workshop', models.BooleanField()),
                ('employees', models.IntegerField()),
                ('stock', models.CharField(max_length=100)),
                ('has_showcase', models.BooleanField()),
                ('showcase_description', models.CharField(max_length=500)),
                ('shopping_center', models.CharField(max_length=100)),
                ('regular_suppliers', models.CharField(max_length=500)),
                ('billing', models.FloatField()),
            ],
        ),
    ]
