# Generated by Django 3.1.2 on 2021-01-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='employees',
        ),
        migrations.AddField(
            model_name='contacts',
            name='employees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='request_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
