# Generated by Django 3.1.2 on 2021-01-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_auto_20210129_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_ended',
        ),
        migrations.AddField(
            model_name='visit',
            name='state',
            field=models.IntegerField(null=True),
        ),
    ]
