# Generated by Django 3.1.2 on 2021-01-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_auto_20210129_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
