# Generated by Django 3.1.2 on 2021-02-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_offert'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='volume',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
