# Generated by Django 3.1.2 on 2021-02-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0055_visit_visit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='billing',
        ),
    ]
