# Generated by Django 3.1.2 on 2021-02-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_auto_20210203_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='regular_suppliers',
        ),
    ]
