# Generated by Django 3.1.2 on 2021-02-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_visit_request_observations'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='ext_commercial',
            field=models.IntegerField(null=True),
        ),
    ]
