# Generated by Django 3.1.2 on 2021-02-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_visit_ext_commercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
