# Generated by Django 3.1.2 on 2021-02-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_auto_20210204_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='company_id',
        ),
    ]
