# Generated by Django 3.1.2 on 2021-02-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_remove_visit_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='payment_id_ADN',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='phone_seller',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='rep_id_ADN',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='tariff_id_ADN',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='web_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
