# Generated by Django 3.1.2 on 2021-02-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_auto_20210208_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='cod',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
