# Generated by Django 3.1.2 on 2021-02-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_address_paid_freight'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_state', models.IntegerField()),
                ('id_country', models.IntegerField()),
                ('id_zone', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('iso_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='payment_id_ADN',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='rep_id_ADN',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='tariff_id_ADN',
        ),
    ]
