# Generated by Django 3.1.2 on 2021-02-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_auto_20210208_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='id_state',
        ),
    ]
