# Generated by Django 3.1.2 on 2021-02-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_remove_state_id_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zone', models.IntegerField()),
                ('id_currency', models.IntegerField()),
                ('iso_code', models.IntegerField()),
                ('call_prefix', models.IntegerField()),
                ('contains_states', models.BooleanField(default=False)),
                ('need_identification_number', models.BooleanField(default=False)),
                ('need_zip_code', models.BooleanField(default=False)),
                ('zip_code_format', models.CharField(max_length=30)),
                ('display_tax_labe', models.BooleanField(default=False)),
            ],
        ),
    ]
