# Generated by Django 3.1.2 on 2021-02-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_country_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(max_length=5),
        ),
    ]
