# Generated by Django 3.1.2 on 2021-02-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0073_auto_20210209_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_currency',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
