# Generated by Django 3.1.2 on 2021-02-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_country_iso_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.IntegerField(),
        ),
    ]
