# Generated by Django 3.1.2 on 2021-02-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_auto_20210209_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='expiration_days_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='pag_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='surcharge',
            field=models.FloatField(null=True),
        ),
    ]
