# Generated by Django 3.1.2 on 2021-02-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_auto_20210209_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='old_id',
        ),
    ]
