# Generated by Django 3.1.2 on 2021-02-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_remove_contacts_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.IntegerField(),
        ),
    ]
