# Generated by Django 3.1.2 on 2021-02-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0082_auto_20210212_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='telephone',
            field=models.CharField(max_length=100),
        ),
    ]
