# Generated by Django 3.1.2 on 2021-02-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0083_auto_20210212_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
