# Generated by Django 3.1.2 on 2021-02-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0084_auto_20210212_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
