# Generated by Django 3.1.2 on 2021-02-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0089_auto_20210215_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='rep_id',
            field=models.IntegerField(null=True),
        ),
    ]
