# Generated by Django 3.1.2 on 2021-02-17 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0091_auto_20210216_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
