# Generated by Django 3.1.2 on 2021-02-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0092_note_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='id_dir',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='id_pfj',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
