# Generated by Django 3.1.2 on 2021-02-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0093_auto_20210218_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='codigo_dir_cliente',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
