# Generated by Django 3.1.2 on 2021-02-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0095_contacts_catch_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='user_check',
            field=models.BooleanField(default=False),
        ),
    ]
