# Generated by Django 3.1.2 on 2021-02-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0096_auto_20210223_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='CA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(default=0)),
                ('company_user_id', models.IntegerField(default=0)),
                ('departament_id', models.IntegerField(default=0)),
                ('user_profile', models.IntegerField(default=0)),
                ('role', models.IntegerField(default=0)),
                ('on_use', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='company_user_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='departament_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='role',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_profile',
        ),
    ]
