# Generated by Django 3.1.2 on 2021-02-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0098_ca_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ca',
            name='company_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ca',
            name='partner',
            field=models.BooleanField(default=False),
        ),
    ]
