# Generated by Django 3.1.2 on 2021-02-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0099_auto_20210225_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('owner', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('aproved', models.BooleanField(default=False)),
                ('state', models.IntegerField(default=1)),
                ('departament_id', models.IntegerField(default=0)),
                ('user_profile', models.IntegerField(default=0)),
                ('company_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='verified',
            field=models.BooleanField(default=0),
        ),
    ]
