# Generated by Django 3.1.2 on 2021-02-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0100_auto_20210225_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='verification_url',
            field=models.TextField(blank=True),
        ),
    ]
