# Generated by Django 3.1.2 on 2021-03-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0103_notification_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='portal_key',
            field=models.TextField(blank=True, max_length=128),
        ),
    ]
