# Generated by Django 3.1.2 on 2021-03-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0104_auto_20210305_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
                ('name_product', models.CharField(default='', max_length=300)),
                ('company_id', models.IntegerField(default=0)),
                ('removed', models.BooleanField(default=True)),
            ],
        ),
    ]
