# Generated by Django 3.1.2 on 2021-03-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0108_purchasedocument_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='avg_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='family',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='last_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='last_purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='purchase_15_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='purchase_30_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='purchase_60_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='purchases',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='sales',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='seller',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='stock_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='stock_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='tipoArt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='total_current_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='total_last_year',
            field=models.IntegerField(null=True),
        ),
    ]
