# Generated by Django 3.1.2 on 2021-03-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0109_auto_20210310_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedocumentcontent',
            name='reference',
            field=models.CharField(max_length=100),
        ),
    ]
