# Generated by Django 3.1.2 on 2021-03-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0110_auto_20210310_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='current_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='last_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='quarter',
            field=models.IntegerField(null=True),
        ),
    ]
