# Generated by Django 3.1.2 on 2021-03-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0111_auto_20210310_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='current_month_update',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='supplier_price',
            field=models.FloatField(null=True),
        ),
    ]
