# Generated by Django 3.1.2 on 2021-03-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0112_auto_20210311_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedocumentcontent',
            name='supplier_price',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
