# Generated by Django 3.1.2 on 2021-03-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0113_auto_20210312_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.TextField(blank=True),
        ),
    ]
