# Generated by Django 3.1.2 on 2021-03-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0114_notification_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocumentcontent',
            name='t3',
            field=models.FloatField(null=True),
        ),
    ]
