# Generated by Django 3.1.2 on 2021-03-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0115_purchasedocumentcontent_t3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedocumentcontent',
            name='purchase_15_days',
        ),
        migrations.AlterField(
            model_name='purchasedocumentcontent',
            name='avg_cost',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedocumentcontent',
            name='last_cost',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedocumentcontent',
            name='stock',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedocumentcontent',
            name='t3',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
