# Generated by Django 3.1.2 on 2021-03-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0116_auto_20210316_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
