# Generated by Django 3.1.2 on 2021-03-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0117_account_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='BA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('board_id', models.IntegerField()),
                ('edit', models.BooleanField(default=False)),
                ('store', models.BooleanField(default=False)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('owner', models.IntegerField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('background', models.ImageField(upload_to='board/')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('list_id', models.IntegerField()),
                ('deadline', models.DateField()),
                ('issue', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('owner_id', models.IntegerField()),
                ('members', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('board_id', models.IntegerField()),
                ('labels', models.TextField(null=True)),
            ],
        ),
    ]
