# Generated by Django 3.1.2 on 2021-03-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0119_auto_20210322_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='BA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('board_id', models.IntegerField()),
                ('edit', models.BooleanField(default=True)),
                ('store', models.BooleanField(default=True)),
                ('removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('owner', models.IntegerField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('background', models.ImageField(null=True, upload_to='')),
                ('removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('board_id', models.IntegerField(null=True)),
                ('list_id', models.IntegerField()),
                ('deadline', models.DateField(null=True)),
                ('issue', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('owner_id', models.IntegerField()),
                ('members', models.TextField(default=',', null=True)),
                ('labels', models.TextField(default=',', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('board_id', models.IntegerField()),
                ('removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
