# Generated by Django 3.1.2 on 2021-03-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0120_ba_board_card_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('departament_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('date_type', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=80)),
                ('start_date', models.DateField()),
                ('start_hour', models.TimeField(null=True)),
                ('finish_date', models.DateField(null=True)),
                ('finish_hour', models.TimeField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('repeat', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('inc_id', models.IntegerField()),
                ('content', models.CharField(max_length=400, null=True)),
                ('date', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaidVacations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
