# Generated by Django 3.1.2 on 2021-03-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0121_calendar_commentaries_paidvacations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryTranslations',
            new_name='CategoryLang',
        ),
        migrations.RenameModel(
            old_name='FeatureValueTranslation',
            new_name='FeatureLang',
        ),
        migrations.RenameModel(
            old_name='FeatureTranslation',
            new_name='FeatureValueLang',
        ),
        migrations.RenameModel(
            old_name='ProductTanslations',
            new_name='ProductLang',
        ),
        migrations.RemoveField(
            model_name='featurelang',
            name='feature_value_id',
        ),
        migrations.RemoveField(
            model_name='featurevaluelang',
            name='feature_id',
        ),
        migrations.AddField(
            model_name='featurelang',
            name='feature_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='featurevaluelang',
            name='feature_value_id',
            field=models.IntegerField(default=0),
        ),
    ]
