# Generated by Django 3.1.2 on 2021-03-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0122_auto_20210324_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylang',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
