# Generated by Django 3.1.2 on 2021-03-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0123_categorylang_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_company_id',
            field=models.IntegerField(default=0),
        ),
    ]
