# Generated by Django 3.1.2 on 2021-03-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0124_category_category_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categorylang',
            name='friendly_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='categorylang',
            name='meta_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='categorylang',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='categorylang',
            name='meta_words',
            field=models.TextField(blank=True),
        ),
    ]
