# Generated by Django 3.1.2 on 2021-03-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0125_auto_20210325_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
