# Generated by Django 3.1.2 on 2021-03-29 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0126_auto_20210329_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_company_id',
            new_name='company_category_id',
        ),
    ]
