# Generated by Django 3.1.2 on 2021-04-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0128_auto_20210406_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
