# Generated by Django 3.1.2 on 2021-04-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0129_testingreport_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='check_config',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companies',
            name='end_day',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='companies',
            name='logo',
            field=models.ImageField(null=True, upload_to='dashboard/media/company_logo/'),
        ),
        migrations.AddField(
            model_name='companies',
            name='max_vacations',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='companies',
            name='min_vacations',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='companies',
            name='start_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='companies',
            name='vacation_days',
            field=models.IntegerField(default=23),
        ),
        migrations.AddField(
            model_name='companies',
            name='vacations_range',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(null=True, upload_to='dashboard/media/board/'),
        ),
    ]
