# Generated by Django 3.1.2 on 2021-04-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0130_auto_20210407_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingreport',
            name='phone_data',
            field=models.TextField(blank=True),
        ),
    ]
