# Generated by Django 3.1.2 on 2021-04-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0131_testingreport_phone_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testingreport',
            name='phone_data',
        ),
        migrations.AlterField(
            model_name='testingreport',
            name='template_id',
            field=models.TextField(blank=True),
        ),
    ]
