# Generated by Django 3.1.2 on 2021-04-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0133_auto_20210408_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingtemplate',
            name='supplier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
