# Generated by Django 3.1.2 on 2021-04-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0134_testingtemplate_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testingtemplate',
            name='meassures',
        ),
        migrations.AddField(
            model_name='testingtemplate',
            name='mx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='testingtemplate',
            name='my',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='testingtemplate',
            name='mz',
            field=models.FloatField(null=True),
        ),
    ]
