# Generated by Django 3.1.2 on 2021-04-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0137_auto_20210412_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonetesting',
            name='correct',
            field=models.BooleanField(null=True),
        ),
    ]
