# Generated by Django 3.1.2 on 2021-04-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0138_phonetesting_correct'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialBudgets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('consultedPrice', models.FloatField()),
                ('finalPrice', models.FloatField()),
                ('units', models.IntegerField()),
                ('typeQuery', models.IntegerField(default=0)),
                ('commercialMail', models.EmailField(max_length=60)),
                ('commercialName', models.CharField(max_length=50)),
                ('accepted', models.IntegerField(default=0)),
                ('quantityAvailable', models.IntegerField()),
                ('customerBudget', models.CharField(default='Sin cliente', max_length=50)),
                ('temporary', models.BooleanField(default=0)),
                ('availableDate', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='parttesting',
            name='meassures',
        ),
        migrations.AddField(
            model_name='parttesting',
            name='mx',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parttesting',
            name='my',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parttesting',
            name='mz',
            field=models.FloatField(null=True),
        ),
    ]
