# Generated by Django 3.1.2 on 2021-04-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0139_auto_20210412_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttesting',
            name='image',
            field=models.ImageField(null=True, upload_to='quality/component_errors/'),
        ),
        migrations.AlterField(
            model_name='phonetesting',
            name='image',
            field=models.ImageField(null=True, upload_to='quality/phone_errors/'),
        ),
    ]
