# Generated by Django 3.1.2 on 2021-04-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0141_auto_20210413_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidences',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='incidences',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='incidences',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='incidences',
            name='rep_id',
        ),
        migrations.RemoveField(
            model_name='incidences',
            name='title',
        ),
        migrations.AddField(
            model_name='account',
            name='pending_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commercialbudgets',
            name='answer_user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incidences',
            name='boss_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidences',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incidences',
            name='destination_departament_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incidences',
            name='issue',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='incidences',
            name='priority',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incidences',
            name='source_departament_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incidences',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='logo',
            field=models.ImageField(null=True, upload_to='company_logo/'),
        ),
        migrations.AlterField(
            model_name='incidences',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
    ]
