# Generated by Django 3.1.2 on 2021-04-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0142_auto_20210415_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.ImageField(upload_to='')),
            ],
        ),
    ]
