# Generated by Django 3.1.2 on 2021-04-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0143_domainkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTestingMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField()),
                ('resource', models.FileField(null=True, upload_to='quality/component_errors/')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneTestingMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField()),
                ('resource', models.FileField(null=True, upload_to='quality/phone_errors/')),
            ],
        ),
        migrations.RemoveField(
            model_name='parttesting',
            name='image',
        ),
        migrations.RemoveField(
            model_name='phonetesting',
            name='image',
        ),
    ]
