# Generated by Django 3.1.2 on 2021-04-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0145_auto_20210419_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetesting',
            name='has_media',
            field=models.BooleanField(default=False),
        ),
    ]
