# Generated by Django 3.1.2 on 2021-04-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0147_auto_20210421_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttestingentry',
            name='company_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testingreport',
            name='dte_id',
            field=models.IntegerField(null=True),
        ),
    ]
