# Generated by Django 3.1.2 on 2021-04-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0148_auto_20210421_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingreport',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testingreport',
            name='stt',
            field=models.IntegerField(null=True),
        ),
    ]
