# Generated by Django 3.1.2 on 2021-04-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0149_auto_20210421_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttestingentry',
            name='supplier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
