# Generated by Django 3.1.2 on 2021-05-06 15:24

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0151_auto_20210422_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(default=0)),
                ('product_id', models.IntegerField(default=0)),
                ('tariff_name', models.CharField(default=' ', max_length=100)),
                ('no_iva_sale_price', models.FloatField(null=True)),
                ('tax_rule', models.IntegerField(default=0, null=True)),
                ('iva_sale_price', models.FloatField(null=True)),
                ('unit_price', models.FloatField(null=True)),
                ('discount_shown', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTransport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(default=0)),
                ('product_id', models.IntegerField(default=0)),
                ('package_width', models.FloatField(default=0, null=True)),
                ('package_height', models.FloatField(default=0, null=True)),
                ('package_depth', models.FloatField(default=0, null=True)),
                ('package_weight', models.FloatField(default=0, null=True)),
                ('shipment_cost', models.FloatField(default=0, null=True)),
                ('avaliable_carriers', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('carrier', models.CharField(max_length=50)),
                ('suplier', models.CharField(max_length=50)),
                ('order_id', models.CharField(max_length=50)),
                ('number_of_packages', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('has_media', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking', models.IntegerField()),
                ('tracking_img', models.ImageField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default=' ', max_length=750),
        ),
        migrations.AddField(
            model_name='product',
            name='ean_13_barcode',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='friendly_url',
            field=models.CharField(default=' ', max_length=350),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(default=' ', max_length=350),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(default=' ', max_length=350),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='p_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price_shown',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_avaliable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='upc_barcode',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tariff',
            name='tax_rule',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='documenttestingentry',
            name='rma',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='documenttestingentry',
            name='tested_q',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='documenttestingentry',
            name='valid_q',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
    ]
