# Generated by Django 3.1.7 on 2021-05-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0153_auto_20210507_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialbudgets',
            name='quantity_available',
            field=models.IntegerField(null=True),
        ),
    ]
