# Generated by Django 3.1.7 on 2021-05-10 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0154_auto_20210507_1227'),
        ('dashboard', '0155_auto_20210507_1718'),
    ]

    operations = [
    ]
