# Generated by Django 3.1.2 on 2021-05-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0156_merge_20210510_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_call', models.TimeField(null=True)),
                ('shedule', models.CharField(max_length=50)),
            ],
        ),
    ]
