# Generated by Django 3.1.2 on 2021-05-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0158_remove_schedulelog_last_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulelog',
            name='last_call',
            field=models.DateTimeField(null=True),
        ),
    ]
