# Generated by Django 3.1.7 on 2021-05-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0159_schedulelog_last_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierIncidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('client_id', models.IntegerField()),
                ('shipment_number', models.IntegerField()),
                ('incidende_date', models.DateTimeField(auto_now=True)),
                ('color', models.IntegerField(default=0)),
                ('client_bill', models.CharField(max_length=100)),
                ('carrier_bill', models.CharField(max_length=100)),
                ('incidence_type', models.IntegerField(default=0)),
                ('coment', models.CharField(max_length=500)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
    ]
