# Generated by Django 3.1.7 on 2021-05-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0160_carrierincidence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrierincidence',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='carrierincidence',
            name='company_id',
        ),
        migrations.AddField(
            model_name='carrierincidence',
            name='client',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='carrierincidence',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carrierincidence',
            name='carrier_bill',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carrierincidence',
            name='client_bill',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carrierincidence',
            name='color',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='carrierincidence',
            name='coment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='carrierincidence',
            name='incidence_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carrierincidence',
            name='incidende_date',
            field=models.DateTimeField(),
        ),
    ]
