# Generated by Django 3.1.7 on 2021-05-12 08:46

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0161_auto_20210511_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialBudgetMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField()),
                ('budget_img', models.ImageField()),
            ],
        ),
        migrations.AddField(
            model_name='commercialbudgets',
            name='has_media',
            field=models.BooleanField(default=False),
        ),
    ]
