# Generated by Django 3.1.7 on 2021-05-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0162_auto_20210511_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierincidence',
            name='incidence_date',
            field=models.DateField(),
        ),
    ]
