# Generated by Django 3.1.7 on 2021-05-12 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0164_merge_20210512_1638'),
        ('dashboard', '0164_merge_20210512_1628'),
        ('dashboard', '0164_merge_20210512_1724'),
    ]

    operations = [
    ]
