# Generated by Django 3.1.7 on 2021-05-13 07:46

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0165_merge_20210512_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidencesMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incidence', models.IntegerField()),
                ('incidence_img', models.ImageField(upload_to=dashboard.models.IncidencesMedia.get_path)),
            ],
        ),
        migrations.AddField(
            model_name='incidences',
            name='has_media',
            field=models.BooleanField(default=False),
        ),
    ]
