# Generated by Django 3.1.2 on 2021-05-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0166_auto_20210513_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
