# Generated by Django 3.1.7 on 2021-05-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0167_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='worker_number',
            field=models.IntegerField(null=True),
        ),
    ]
