# Generated by Django 3.1.2 on 2021-05-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0168_visit_worker_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='last_visit_date',
            field=models.DateField(null=True),
        ),
    ]
