# Generated by Django 3.1.7 on 2021-05-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0168_visit_worker_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialbudgets',
            name='observations',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
