# Generated by Django 3.1.2 on 2021-05-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0170_auto_20210518_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='worker_number',
            field=models.IntegerField(null=True),
        ),
    ]
