# Generated by Django 3.1.2 on 2021-05-18 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0171_auto_20210518_0941'),
        ('dashboard', '0169_compatiblemodels'),
    ]

    operations = [
    ]
