# Generated by Django 3.1.7 on 2021-05-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0172_merge_20210518_1028'),
        ('dashboard', '0169_commercialbudgets_observations'),
    ]

    operations = [
    ]
