# Generated by Django 3.1.2 on 2021-05-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0173_merge_20210518_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
