# Generated by Django 3.1.7 on 2021-05-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0174_auto_20210518_1721'),
        ('dashboard', '0173_merge_20210518_1657'),
    ]

    operations = [
    ]
