# Generated by Django 3.1.2 on 2021-05-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0176_commercialbudgets_shopping_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compatiblemodels',
            name='compatibleCodigo',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='compatiblemodels',
            name='compatibleModelo',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='compatiblemodels',
            name='duplicar',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='compatiblemodels',
            name='tituloAdn',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='compatiblemodels',
            name='urlImage',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
