# Generated by Django 3.1.2 on 2021-05-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0177_auto_20210519_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compatiblemodels',
            name='compatibleCodigo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compatiblemodels',
            name='compatibleModelo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compatiblemodels',
            name='descripcionCorta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compatiblemodels',
            name='descripcionLarga',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compatiblemodels',
            name='duplicar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compatiblemodels',
            name='tituloAdn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compatiblemodels',
            name='urlImage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
