# Generated by Django 3.1.2 on 2021-05-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0178_auto_20210519_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ca',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
