# Generated by Django 3.1.2 on 2021-05-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0179_auto_20210519_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commercialbudgets',
            name='commercial_mail',
        ),
        migrations.RemoveField(
            model_name='commercialbudgets',
            name='commercial_name',
        ),
        migrations.AddField(
            model_name='commercialbudgets',
            name='request_user',
            field=models.IntegerField(null=True),
        ),
    ]
