# Generated by Django 3.1.2 on 2021-05-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0180_auto_20210520_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.IntegerField(null=True),
        ),
    ]
