# Generated by Django 3.1.2 on 2021-05-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0184_commercialbudgetmedia_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialbudgetmedia',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
