# Generated by Django 3.1.2 on 2021-05-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0185_auto_20210523_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialbudgets',
            name='available_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commercialbudgets',
            name='customer_budget',
            field=models.TextField(default='Sin cliente'),
        ),
        migrations.AlterField(
            model_name='commercialbudgets',
            name='observations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commercialbudgets',
            name='reference',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commercialbudgets',
            name='shopping_observations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='commercialbudgets',
            name='title',
            field=models.TextField(),
        ),
    ]
