# Generated by Django 3.1.2 on 2021-05-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0186_auto_20210523_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='ending_date',
            field=models.DateField(null=True),
        ),
    ]
