# Generated by Django 3.1.2 on 2021-05-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0189_auto_20210525_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='internal_observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='offert',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='request_observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='showcase_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
