# Generated by Django 3.1.2 on 2021-05-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0190_auto_20210527_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='doc_036',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='doc_resell',
            field=models.TextField(blank=True, null=True),
        ),
    ]
