# Generated by Django 3.1.2 on 2021-06-03 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0192_callschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallSchedule',
        ),
    ]
