# Generated by Django 3.1.2 on 2021-06-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0193_delete_callschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
