# Generated by Django 3.1.2 on 2021-06-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0194_notification_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notified',
            field=models.BooleanField(default=True),
        ),
    ]
