# Generated by Django 3.1.2 on 2021-06-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0195_auto_20210603_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='mail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='tel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
