# Generated by Django 3.1.2 on 2021-06-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0196_auto_20210604_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='ca',
            name='mirror',
            field=models.IntegerField(default=0),
        ),
    ]
