# Generated by Django 3.1.2 on 2021-06-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0197_ca_mirror'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='status_pre_catchment',
            field=models.IntegerField(null=True),
        ),
    ]
