# Generated by Django 3.1.2 on 2021-06-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0199_commercialbudgets_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='highCostSF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField()),
                ('supplier', models.IntegerField()),
                ('families', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='otherCallObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField()),
                ('observation', models.TextField()),
            ],
        ),
    ]
