# Generated by Django 3.1.2 on 2021-06-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0200_highcostsf_othercallobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='buys_no_iva',
            field=models.BooleanField(default=False),
        ),
    ]
