# Generated by Django 3.1.2 on 2021-06-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0201_contacts_buys_no_iva'),
    ]

    operations = [
        migrations.CreateModel(
            name='callScheduleCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=150)),
            ],
        ),
    ]
