# Generated by Django 3.1.2 on 2021-06-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0202_callschedulecause'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cause',
            field=models.IntegerField(default=0),
        ),
    ]
