# Generated by Django 3.1.2 on 2021-06-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0203_notification_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='metadata',
            field=models.TextField(blank=True),
        ),
    ]
