# Generated by Django 3.2.4 on 2021-07-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0205_contactmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='track_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
