# Generated by Django 3.2.4 on 2021-07-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0206_tracking_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
