# Generated by Django 3.2.4 on 2021-07-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0209_testingreport_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='completed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='references',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='number_of_packages',
            field=models.CharField(max_length=50),
        ),
    ]
