# Generated by Django 3.2.4 on 2021-07-13 11:06

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0212_rename_preocessed_packages_tracking_processed_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField(default=0)),
                ('user', models.IntegerField()),
                ('email', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('nif', models.CharField(blank=True, default='', max_length=20)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=200)),
                ('imei', models.CharField(blank=True, default='', max_length=100)),
                ('pattern', models.CharField(blank=True, default='', max_length=50)),
                ('failure', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('observations', models.TextField(blank=True, default='')),
                ('base', models.FloatField()),
                ('total', models.FloatField()),
                ('content', models.TextField(blank=True, default='')),
                ('signature', models.TextField(blank=True, default='')),
                ('media', models.FileField(null=True)),
                ('state', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
