# Generated by Django 3.1.2 on 2021-07-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0213_satentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('members', models.TextField(default=',', null=True)),
                ('removed', models.BooleanField(default=False)),
                ('is_group', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=30, null=True)),
                ('logo', models.ImageField(null=True, upload_to='dashboard/media/group_logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('source', models.IntegerField()),
                ('content', models.TextField(max_length=500)),
                ('conversation_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
