# Generated by Django 3.2.4 on 2021-07-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0214_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='satentry',
            name='finish_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='satentry',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
