# Generated by Django 3.1.2 on 2021-07-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0215_auto_20210721_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='satentry',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
