# Generated by Django 3.1.2 on 2021-07-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0216_satentry_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='satentry',
            name='company_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
