# Generated by Django 3.1.2 on 2021-07-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0217_satentry_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='satentry',
            name='send_mail',
            field=models.BooleanField(default=False),
        ),
    ]
