# Generated by Django 3.2.4 on 2021-07-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0218_satentry_send_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='observation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
