# Generated by Django 3.1.2 on 2021-07-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0219_tracking_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='satentry',
            name='iva',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='satentry',
            name='total_iva',
            field=models.FloatField(null=True),
        ),
    ]
