# Generated by Django 3.2.4 on 2021-07-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0220_auto_20210723_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttesting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
