# Generated by Django 3.1.2 on 2021-07-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0221_parttesting_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='satentry',
            name='tariff',
            field=models.IntegerField(null=True),
        ),
    ]
