# Generated by Django 3.1.2 on 2021-07-26 10:45

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0223_auto_20210726_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.IntegerField()),
                ('entry_media', models.ImageField()),
            ],
        ),
    ]
