# Generated by Django 3.1.2 on 2021-07-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0225_auto_20210727_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='issue',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
