# Generated by Django 3.2.4 on 2021-07-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0226_auto_20210727_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialbudgets',
            name='adn_reference',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='commercialbudgets',
            name='has_reference',
            field=models.BooleanField(default=False),
        ),
    ]
