# Generated by Django 3.1.2 on 2021-07-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0230_auto_20210730_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satentry',
            name='changed_state',
            field=models.BooleanField(null=True),
        ),
    ]
