# Generated by Django 3.1.2 on 2021-08-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0231_auto_20210730_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_pass',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='signature',
            field=models.TextField(null=True),
        ),
    ]
