# Generated by Django 3.1.2 on 2021-08-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0232_auto_20210803_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalProductsAdn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30)),
                ('art', models.TextField(blank=True, default='')),
                ('tariff', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
