# Generated by Django 3.1.2 on 2021-08-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0233_temporalproductsadn'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporalproductsadn',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
