# Generated by Django 3.1.2 on 2021-08-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0234_temporalproductsadn_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporalproductsadn',
            name='company_id',
            field=models.IntegerField(default=0),
        ),
    ]
