# Generated by Django 3.1.2 on 2021-08-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0236_temporalproductsadn_refused'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporalproductsadn',
            name='replacement_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
