# Generated by Django 3.2.4 on 2021-08-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0237_temporalproductsadn_replacement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='international',
            field=models.BooleanField(null=True),
        ),
    ]
