# Generated by Django 3.2.4 on 2021-08-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0238_tracking_international'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
