# Generated by Django 3.2.4 on 2021-08-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0241_tracking_force_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='group',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tracking',
            name='grouped',
            field=models.BooleanField(default=False),
        ),
    ]
