# Generated by Django 3.1.6 on 2021-08-30 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0242_auto_20210827_1642'),
        ('dashboard', '0242_auto_20210830_1029'),
    ]

    operations = [
    ]
