# Generated by Django 3.2.4 on 2021-08-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0243_merge_20210830_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='cif',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='cod_adn',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='country',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='removed',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='updated_at',
        ),
    ]
