# Generated by Django 3.2.4 on 2021-08-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0244_auto_20210830_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
