# Generated by Django 3.2.4 on 2021-09-03 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0246_suppliercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='tariff_wr',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
