# Generated by Django 3.2.4 on 2021-09-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0249_tracking_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrierincidence',
            name='shipment_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
