# Generated by Django 3.2.4 on 2021-09-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0250_alter_carrierincidence_shipment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='carrier',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='order_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='suplier',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='track_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
