# Generated by Django 3.2.4 on 2021-09-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0251_alter_tracking_order_id'),
        ('dashboard', '0251_auto_20210927_1156'),
    ]

    operations = [
    ]
