# Generated by Django 3.2.7 on 2021-09-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0252_merge_20210927_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingmedia',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='order_id',
            field=models.TextField(),
        ),
    ]
