# Generated by Django 3.2.7 on 2021-10-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0254_websearch_websearchclick'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeBudgetState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('budget_id', models.IntegerField()),
                ('prev_state', models.IntegerField()),
                ('new_state', models.IntegerField()),
                ('user', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
