# Generated by Django 3.2.7 on 2021-10-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0255_changebudgetstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSuppliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('supplier_id', models.IntegerField()),
                ('reference', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
