# Generated by Django 3.2.7 on 2021-10-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0256_budgetsuppliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialbudgets',
            name='responsable',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='commercialbudgets',
            name='supplier',
            field=models.IntegerField(null=True),
        ),
    ]
