# Generated by Django 3.2.4 on 2021-10-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0257_auto_20211013_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('reference', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BudgetSuppliers',
        ),
    ]
