# Generated by Django 3.2.4 on 2021-10-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0258_auto_20211013_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialbudgets',
            name='web_budget',
            field=models.BooleanField(default=False),
        ),
    ]
