# Generated by Django 3.2.4 on 2021-10-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0259_commercialbudgets_web_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='websearch',
            name='session_key',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
