# Generated by Django 3.2.4 on 2021-10-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0260_websearch_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='websearchclick',
            name='added_to_cart',
            field=models.BooleanField(default=False),
        ),
    ]
