# Generated by Django 3.2.4 on 2021-10-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0261_websearchclick_added_to_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='websearch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='websearchclick',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
