# Generated by Django 3.2.7 on 2021-11-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0264_auto_20211019_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialbudgets',
            name='internal_comment',
            field=models.TextField(null=True),
        ),
    ]
