# Generated by Django 3.2.7 on 2022-01-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0266_changecommercialobjetives_commercialobjetives'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialbudgets',
            name='incidence',
            field=models.TextField(null=True),
        ),
    ]
