# Generated by Django 3.2.4 on 2022-01-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0267_commercialbudgets_incidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departament_id', models.IntegerField()),
                ('manual', models.FileField(upload_to='')),
            ],
        ),
    ]
