# Generated by Django 3.2.4 on 2022-01-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0268_qualitymanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitymanual',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
