# Generated by Django 3.2.7 on 2022-02-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0269_qualitymanual_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidences',
            name='assigned',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='incidences',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
