# Generated by Django 3.2.4 on 2022-02-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0270_auto_20220204_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitymanual',
            name='group',
            field=models.IntegerField(default=0),
        ),
    ]
