# Generated by Django 3.2.7 on 2022-02-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0271_qualitymanual_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidences',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
