# Generated by Django 3.2.7 on 2022-04-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0274_booking_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(null=True)),
                ('check_in_edited', models.DateTimeField(null=True)),
                ('check_out_edited', models.DateTimeField(null=True)),
                ('aproved', models.BooleanField(default=0)),
                ('deleted', models.BooleanField(default=0)),
                ('device', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebServiceSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=40)),
                ('apikey', models.CharField(max_length=100)),
                ('ult_rest_apikey', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
