# Generated by Django 3.2.7 on 2022-04-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0275_checkindata_webservicesupplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservicesupplier',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
