# Generated by Django 3.2.7 on 2022-04-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0277_alter_webservicesupplier_ult_rest_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webservicesupplier',
            name='ult_rest_apikey',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
