# Generated by Django 3.2.7 on 2022-04-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0278_alter_webservicesupplier_ult_rest_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebServiceTraceability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_wss', models.IntegerField()),
                ('action', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
