# Generated by Django 3.2.7 on 2022-04-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0279_webservicetraceability'),
    ]

    operations = [
        migrations.AddField(
            model_name='webservicetraceability',
            name='reference',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
