# Generated by Django 3.2.7 on 2022-04-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0280_webservicetraceability_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialobjetives',
            name='quarter',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commercialobjetives',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
