# Generated by Django 3.2.7 on 2022-04-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0281_auto_20220429_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='pastObjetive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('tphox', models.FloatField(null=True)),
                ('reds', models.FloatField(null=True)),
                ('scooter', models.FloatField(null=True)),
                ('laptop', models.FloatField(null=True)),
                ('qcharx', models.FloatField(null=True)),
                ('active', models.FloatField(null=True)),
            ],
        ),
    ]
