# Generated by Django 3.2.7 on 2022-05-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0282_pastobjetive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkindata',
            name='device',
        ),
        migrations.AddField(
            model_name='checkindata',
            name='device_in',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='checkindata',
            name='device_out',
            field=models.IntegerField(null=True),
        ),
    ]
