# Generated by Django 3.2.7 on 2022-05-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0283_auto_20220505_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkindata',
            name='manually',
            field=models.BooleanField(default=0, null=True),
        ),
    ]
