# Generated by Django 3.2.7 on 2022-05-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0284_checkindata_manually'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='work_hours',
            field=models.IntegerField(default=8, null=True),
        ),
    ]
