# Generated by Django 3.2.7 on 2022-06-01 17:56

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0285_account_work_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('state', models.IntegerField(default=0)),
                ('reference', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('reason', models.IntegerField()),
                ('sales_proposal', models.CharField(max_length=500, null=True)),
                ('proposal_date', models.DateField(auto_now=True, null=True)),
                ('purchases_response', models.CharField(max_length=500, null=True)),
                ('response_date', models.DateField(null=True)),
                ('responsable', models.CharField(max_length=30, null=True)),
                ('has_media', models.BooleanField(default=False)),
                ('deleted', models.IntegerField(default=0)),
                ('repeated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.IntegerField()),
                ('proposal_img', models.ImageField()),
            ],
        ),
        migrations.CreateModel(
            name='ProposalTraceability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_id', models.IntegerField()),
                ('prev_state', models.IntegerField()),
                ('new_state', models.IntegerField()),
                ('user', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
