# Generated by Django 3.2.7 on 2022-06-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0286_proposal_proposalmedia_proposaltraceability'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalmedia',
            name='tipo',
            field=models.IntegerField(default=0),
        ),
    ]
