# Generated by Django 3.2.7 on 2022-06-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0288_auto_20220602_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='proposal_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='sales_proposal',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
