# Generated by Django 3.2.7 on 2022-06-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0289_auto_20220602_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='shared',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
