# Generated by Django 3.2.7 on 2022-06-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0290_proposal_shared'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('departament', models.IntegerField()),
                ('absence_type', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=200, null=True)),
                ('start', models.DateField()),
                ('finish', models.DateField()),
                ('state', models.IntegerField(default=0)),
                ('deleted', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
