# Generated by Django 3.2.4 on 2022-08-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0291_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='hidden',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
