# Generated by Django 3.2.4 on 2022-08-31 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0292_proposal_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyObjetive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('tphox', models.FloatField(null=True)),
                ('reds', models.FloatField(null=True)),
                ('scooter', models.FloatField(null=True)),
                ('laptop', models.FloatField(null=True)),
                ('qcharx', models.FloatField(null=True)),
                ('active', models.FloatField(null=True)),
                ('catchment', models.FloatField(null=True)),
            ],
        ),
    ]
