# Generated by Django 3.2.4 on 2022-09-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0295_dailyobjetivetraceability'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliveryIncidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(null=True)),
                ('inc_type', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('request_user', models.IntegerField(null=True)),
                ('client_id', models.IntegerField(null=True)),
                ('client_name', models.CharField(max_length=100, null=True)),
                ('destination', models.IntegerField(null=True)),
                ('fac_client', models.CharField(max_length=100, null=True)),
                ('fac_carrier', models.CharField(max_length=100, null=True)),
                ('delivery_number', models.CharField(max_length=100, null=True)),
                ('observations', models.TextField(max_length=800, null=True)),
            ],
        ),
    ]
