# Generated by Django 3.2.4 on 2022-09-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0296_deliveryincidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyobjetive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
