# Generated by Django 3.2.4 on 2022-09-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0297_dailyobjetive_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyobjetivetraceability',
            name='laptop_new',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dailyobjetivetraceability',
            name='qcharx_new',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dailyobjetivetraceability',
            name='reds_new',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dailyobjetivetraceability',
            name='scooter_new',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dailyobjetivetraceability',
            name='tphox_new',
            field=models.FloatField(null=True),
        ),
    ]
