# Generated by Django 3.2.4 on 2022-09-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0298_auto_20220919_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryincidence',
            name='article_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
