# Generated by Django 3.2.4 on 2022-09-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0299_deliveryincidence_article_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryincidence',
            name='nserie',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
