# Generated by Django 3.2.4 on 2022-09-21 15:37

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0300_deliveryincidence_nserie'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryIncidenceMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_incidence_id', models.IntegerField()),
                ('type', models.IntegerField(default=0)),
                ('file', models.FileField()),
            ],
        ),
    ]
