# Generated by Django 3.2.4 on 2022-09-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0301_deliveryincidencemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialbudgets',
            name='customer_name',
            field=models.TextField(null=True),
        ),
    ]
