# Generated by Django 3.2.4 on 2022-11-08 08:19

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0303_alter_tracking_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_id', models.IntegerField()),
                ('file', models.FileField(upload_to=dashboard.models.AbsenceMedia.get_path)),
            ],
        ),
    ]
