# Generated by Django 3.2.4 on 2022-11-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0304_absencemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='vacation_days_next',
            field=models.IntegerField(default=0),
        ),
    ]
