# Generated by Django 3.2.4 on 2022-11-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0307_bartvorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialbudgets',
            name='replacement',
            field=models.BooleanField(default=False),
        ),
    ]
