# Generated by Django 3.2.4 on 2022-12-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0308_commercialbudgets_replacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='bartvorder',
            name='lines',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bartvorder',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bartvorder',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
