# Generated by Django 3.2.4 on 2022-12-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0309_auto_20221215_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='adn_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
