# Generated by Django 3.2.4 on 2023-01-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0310_account_adn_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='company_id',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='checkindata',
            name='company_id',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='commercialbudgets',
            name='company_id',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='deliveryincidence',
            name='company_id',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='company_id',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
