# Generated by Django 4.1.2 on 2023-02-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0310_account_adn_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incidences',
        ),
    ]
