# Generated by Django 4.1.2 on 2023-02-21 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0312_delete_address_delete_ba_delete_bartvorder_delete_bl_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
