# Generated by Django 3.2.4 on 2023-02-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0312_checklocationtraceability'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickersTraceability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField(null=True)),
                ('reference', models.CharField(max_length=50, null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('ub1', models.CharField(max_length=50, null=True)),
                ('ub2', models.CharField(max_length=50, null=True)),
                ('serializar', models.CharField(max_length=50, null=True)),
                ('nserie_check', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('nserie_error', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
