# Generated by Django 3.2.4 on 2023-02-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0313_stickerstraceability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stickerstraceability',
            name='nserie_error',
        ),
        migrations.AddField(
            model_name='stickerstraceability',
            name='nserie_data',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
