# Generated by Django 3.2.4 on 2023-02-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0315_checklocationtraceability_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklocationtraceability',
            name='descripcion',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
