# Generated by Django 4.1.2 on 2023-03-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0317_delete_address_delete_ba_delete_bartvorder_delete_bl_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartTestingMedia',
        ),
        migrations.DeleteModel(
            name='PhoneTestingMedia',
        ),
    ]
