# Generated by Django 4.1.2 on 2023-03-25 13:43

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0318_delete_parttestingmedia_delete_phonetestingmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialbudgetmedia',
            name='budget_img',
            field=models.ImageField(),
        ),
    ]
