# Generated by Django 4.1.2 on 2023-03-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0319_alter_commercialbudgetmedia_budget_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommercialBudgetMedia',
        ),
    ]
