# Generated by Django 4.1.2 on 2023-03-25 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0320_delete_commercialbudgetmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMedia',
        ),
        migrations.DeleteModel(
            name='DeliveryIncidenceMedia',
        ),
        migrations.DeleteModel(
            name='ProposalMedia',
        ),
        migrations.DeleteModel(
            name='SatEntry',
        ),
        migrations.DeleteModel(
            name='SatMedia',
        ),
        migrations.DeleteModel(
            name='TrackingMedia',
        ),
    ]
