# Generated by Django 4.1.2 on 2023-03-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0321_delete_contactmedia_delete_deliveryincidencemedia_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CategoryLang',
        ),
    ]
