# Generated by Django 4.1.2 on 2023-03-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0323_delete_schedulelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
